name: comb_km3net_cta_env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.13
  - pandas
  - pip=23.0
  - pip:
      - astropy==4.0
      - gammapy==0.17
      - ipykernel==6.16.2
      - ipython==7.34.0
      - km3io 
      - km3pipe 
      - km3irf
      - matplotlib==3.2.1
      - naima==0.9.1
      - regions==0.4
